#!/bin/bash

# update repos
sudo apt update

# dependencies
sudo apt install apt-transport-https ca-certificates curl software-properties-common

# Docker GPG keys
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# add Docker registry
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

# check available versions
# apt-cache madison docker-ce


# install docker
sudo apt update /
sudo apt install docker-ce=5:20.10.24~3-0~ubuntu-jammy

# check versions
docker --version
